project:
  type: website

execute:
  freeze: auto

website:
  title: "test-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - new-page.qmd
      - this-is-the-third-pages-of-many-more.qmd
      - about.qmd

format:
  html:
    theme:
      light: [litera, styles.scss]
    toc: true



